// <auto-generated />
using LeagueOfLegendsCharachters.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeagueOfLegendsCharachters.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250704174006_InitalCreate")]
    partial class InitalCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LeagueOfLegendsCharachters.Models.Charachter", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BlueEssence")
                        .HasColumnType("int");

                    b.Property<int>("RolePosition")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("Charachters");
                });

            modelBuilder.Entity("LeagueOfLegendsCharachters.Models.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<int>("Armor")
                        .HasColumnType("int");

                    b.Property<int>("AttackRange")
                        .HasColumnType("int");

                    b.Property<string>("CharachterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("MagicResist")
                        .HasColumnType("int");

                    b.Property<int>("MovementSpeed")
                        .HasColumnType("int");

                    b.HasKey("StatusId");

                    b.HasIndex("CharachterName")
                        .IsUnique();

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("LeagueOfLegendsCharachters.Models.Status", b =>
                {
                    b.HasOne("LeagueOfLegendsCharachters.Models.Charachter", "Charachter")
                        .WithOne("Status")
                        .HasForeignKey("LeagueOfLegendsCharachters.Models.Status", "CharachterName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Charachter");
                });

            modelBuilder.Entity("LeagueOfLegendsCharachters.Models.Charachter", b =>
                {
                    b.Navigation("Status")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
